In [1]:
from speedy import convection

In [2]:
print(convection.diagnose_convection.__doc__)

itop,qdif = diagnose_convection(psa,se,qa,qsat)

Wrapper for ``diagnose_convection``.

Parameters
----------
psa : input rank-2 array('d') with bounds (96,48)
se : input rank-3 array('d') with bounds (96,48,8)
qa : input rank-3 array('d') with bounds (96,48,8)
qsat : input rank-3 array('d') with bounds (96,48,8)

Returns
-------
itop : rank-2 array('i') with bounds (96,48)
qdif : rank-2 array('d') with bounds (96,48)



In [6]:
import numpy as np

psa= np.ones((96, 48))
se = np.ones((96, 48, 8))
qa = np.ones((96, 48, 8))
qsat = np.ones((96, 48, 8))

itop, qdif = convection.diagnose_convection(psa, se, qa, qsat)

print(itop)

[[9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 ...
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]]
